name: Firebase Deployment

on:
  push:
    branches:
      - main  # Asegúrate de que esta sea la rama correcta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # Instalará las dependencias de tu proyecto

      - name: Install Firebase CLI
        run: npm install -g firebase-tools  # Instala Firebase CLI

      - name: Authenticate Firebase CLI with FIREBASE_TOKEN
        run: echo "${{ secrets.FIREBASE_TOKEN }}" | firebase login:ci --token  # Autenticación usando el token desde Secrets

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}  # Despliegue a Firebase Hosting
